FROM mysql:5.7
RUN echo 'sql-mode=""' >> /etc/mysql/conf.d/docker.cnf
RUN echo 'character-set-server=utf8mb4' >> /etc/mysql/conf.d/docker.cnf
RUN echo 'collation-server=utf8mb4_unicode_ci' >> /etc/mysql/conf.d/docker.cnf
